### ISSUE TITLE
Islandora Remote Resource Content Model and collection not installed by default

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_solution_pack_remote_resource#8] opened 2018-05-25 17:28 UTC
In two different VMs I tried enabling this repo (drush en), and got the following error:

> WD islandora: Failed to ingest object:                               [error]
> islandora:sp_remote_resourcecode: 401message: Unauthorized
> WD php: RepositoryException: Unauthorized in                         [error]
> RepositoryConnection->parseFedoraExceptions() (line 229 of
> /var/www/drupal/sites/all/libraries/tuque/RepositoryConnection.php).
> Cannot modify header information - headers already sent by (output   [warning]
> started at /opt/drush-6.3/includes/output.inc:38) bootstrap.inc:1486
> RepositoryException: Unauthorized in RepositoryConnection->parseFedoraExceptions() (line 229 of /var/www/drupal/sites/all/libraries/tuque/RepositoryConnection.php).
> Drush command terminated abnormally due to an unrecoverable error.   [error]

The SP seems to be enabled regardless, but there is no Remote Resource CModel available.

Any idea what's happening?

**Comment by mjordan** [comment] 2018-05-25 17:55
I do not, but I'll take a look.

**Comment by mjordan** [comment] 2018-05-26 20:03
Confirmed. Not sure what's what but you will need to manually install the content model at `admin/islandora/solution_pack_config/solution_packs` until I get some time to look into this, which won't be before mid June. ~As far as I can tell, it's a permissions problem in drush.~

@rosiel using `-u 1` doesn't [solve the problem](https://groups.google.com/d/msg/islandora/i6pU4isI5D8/aW7UChkkCgAJ) for me (i.e., running, `drush -u 1 en -y islandora_solution_pack_remote_resource` results in the cmodel and collection not being installed).

**Comment by rosiel** [comment] 2018-05-27 00:10
@mjordan Forgive me if this is pointing out the obvious. Are you sure that you had completely uninstalled it before trying to `drush en` it again? 

`drush en -y -u 1 islandora_solution_pack_remote_resource` worked for me on a clean machine.

**Comment by mjordan** [comment] 2018-05-27 00:29
@rosiel I forgive you! After uninstalling the remote resource module, in the Drupal sense of "uninstalling", running the command you quote above works as expected. You've solved it. "Obvious" is relative but I tend toward not seeing even the most undeniably obvious. :smiley: 

But I want to make sure that "it" is the same as it is for other solution packs. In other words, do I have to do anything? @bondjimbond I'd appreciate your input here too. Is installing this solution pack and its required objects any different from other solution packs'?

**Comment by bondjimbond** [comment] 2018-05-27 11:54
@mjordan It is different -- except for this one, I have never had to "-u 1" with a Drush command to install a solution pack. Something to add to the readme at least, but do you know why that extra bit is required?

**Comment by rosiel** [comment] 2018-05-27 12:12
By default, the only Drupal user with permission to manage Fedora objects is admin (user 1). I'm not sure what user Drush runs as by default, but it's not user 1. There's a "bridge" (the islandora drupal filter?) that lets Drupal users into Fedora with their Drupal roles/usernames ('administrator' and 'admin' . So while Drush has godly powers in Drupal, Fedora doesn't know who they are and won't let you ingest objects.

All solution packs require it. It's documented (albeit badly) here: https://wiki.duraspace.org/display/ISLANDORA/milestone+5+-++Installing+the+Islandora+Essential+Modules

I propose the wording in the README for all SP's that install objects (i.e. implement hook_islandora_required_objects) where it says "Install as usual" get modified to "Install as a Drupal module; see this for further information. This module installs required Fedora objects, if enabling through Drush, use the administrative user (e.g. `drush en -u 1 islandora_audio`)."

**Comment by bondjimbond** [comment] 2018-05-28 13:04
@rosiel That's good to know - thank you! I agree, such a documentation change would be very helpful. "Install as usual" for most, I think, means either through the Drupal modules UI, or "git clone" and "drush en" unless otherwise specified. I'll open a ticket for that.

**Comment by bondjimbond** [comment] 2018-05-28 13:12
https://jira.duraspace.org/browse/ISLANDORA-2240

**Comment by mjordan** [comment] 2018-06-19 16:10
Closing since this issue is addressed in the JIRA ticket.

**Closed as completed by mjordan** 2018-06-19 16:10 UTC
Labels: bug
